// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"context"
)

type Querier interface {
	CleanupOldEvents(ctx context.Context, dollar_1 interface{}) error
	IsDuplicate(ctx context.Context, arg IsDuplicateParams) (bool, error)
	SaveEvent(ctx context.Context, arg SaveEventParams) error
}

var _ Querier = (*Queries)(nil)
